// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfgr7_BTIaN8EzwGU0NxsWp8C8YxoZQmY',
    appId: '1:815759700050:web:1ffa4f3f2bae8be570ef8b',
    messagingSenderId: '815759700050',
    projectId: 'fitness-tracker-80dc3',
    authDomain: 'fitness-tracker-80dc3.firebaseapp.com',
    storageBucket: 'fitness-tracker-80dc3.appspot.com',
    measurementId: 'G-RH0899VEX9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAO8Z1WmdI2oQngUylPyJRozI4cpkuy2QI',
    appId: '1:815759700050:android:36063e23db18bc5470ef8b',
    messagingSenderId: '815759700050',
    projectId: 'fitness-tracker-80dc3',
    storageBucket: 'fitness-tracker-80dc3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4u188Nik_vmpvdUh86RGuZGw9OVzsCvA',
    appId: '1:815759700050:ios:84dae598cb95bf3e70ef8b',
    messagingSenderId: '815759700050',
    projectId: 'fitness-tracker-80dc3',
    storageBucket: 'fitness-tracker-80dc3.appspot.com',
    iosBundleId: 'com.example.fitnessTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4u188Nik_vmpvdUh86RGuZGw9OVzsCvA',
    appId: '1:815759700050:ios:a465837bdbfabcd870ef8b',
    messagingSenderId: '815759700050',
    projectId: 'fitness-tracker-80dc3',
    storageBucket: 'fitness-tracker-80dc3.appspot.com',
    iosBundleId: 'com.example.fitnessTracker.RunnerTests',
  );
}
